# Generated by Django 5.2.7 on 2025-10-15 06:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paciente_estado_historialmedico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('cobertura', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='recetamedica',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='recetamedica',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='recetamedica',
            name='medicamento',
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='estado',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=10),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, to='api.medicamento'),
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='medico',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.medico'),
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, to='api.medicamento'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.obrasocial'),
        ),
        migrations.DeleteModel(
            name='HistorialMedico',
        ),
    ]
